package ar.tp.dieta;

import org.junit.Before;

@SuppressWarnings("all")
public class TestAccion2 {
  @Before
  public void init() {
    throw new Error("Unresolved compilation problems:"
      + "\nno viable alternative at input \'=\'"
      + "\nno viable alternative at input \'=\'"
      + "\nThe method or field Accion2 is undefined for the type TestAccion2"
      + "\nThe method or field accion is undefined for the type TestAccion2"
      + "\nThe method or field List is undefined for the type TestAccion2"
      + "\nThe method or field recetas is undefined for the type TestAccion2"
      + "\nArrayList cannot be resolved."
      + "\nThe method or field List is undefined for the type TestAccion2"
      + "\nThe method or field usuarios is undefined for the type TestAccion2"
      + "\nArrayList cannot be resolved."
      + "\nThe method or field recetario is undefined for the type TestAccion2"
      + "\nThe method or field mensaje is undefined for the type TestAccion2"
      + "\nThe method or field busqueda1 is undefined for the type TestAccion2"
      + "\nThe method or field basket is undefined for the type TestAccion2"
      + "\nThe method or field usuarioVegano is undefined for the type TestAccion2"
      + "\nThe method or field basket is undefined for the type TestAccion2"
      + "\nThe method or field usuarioVegano is undefined for the type TestAccion2"
      + "\nThe method or field busqueda1 is undefined for the type TestAccion2"
      + "\nThe method or field arrozConPollo is undefined for the type TestAccion2"
      + "\nThe method or field fideosConManteca is undefined for the type TestAccion2"
      + "\nThe method or field lomoMostaza is undefined for the type TestAccion2"
      + "\nThe method or field gelatinaFrambuesa is undefined for the type TestAccion2"
      + "\nThe method or field ensalada is undefined for the type TestAccion2"
      + "\nThe method or field arrozBlanco is undefined for the type TestAccion2"
      + "\nThe method or field recetario is undefined for the type TestAccion2"
      + "\nThe method or field arrozConPollo is undefined for the type TestAccion2"
      + "\nThe method or field recetario is undefined for the type TestAccion2"
      + "\nThe method or field fideosConManteca is undefined for the type TestAccion2"
      + "\nThe method or field recetario is undefined for the type TestAccion2"
      + "\nThe method or field lomoMostaza is undefined for the type TestAccion2"
      + "\nThe method or field recetario is undefined for the type TestAccion2"
      + "\nThe method or field gelatinaFrambuesa is undefined for the type TestAccion2"
      + "\nThe method or field recetario is undefined for the type TestAccion2"
      + "\nThe method or field ensalada is undefined for the type TestAccion2"
      + "\nThe method or field recetario is undefined for the type TestAccion2"
      + "\nThe method or field arrozBlanco is undefined for the type TestAccion2"
      + "\nThe method or field usuarioVegano is undefined for the type TestAccion2"
      + "\nThe method or field recetario is undefined for the type TestAccion2"
      + "\nThe method or field usuarios is undefined for the type TestAccion2"
      + "\nThe method or field usuarioVegano is undefined for the type TestAccion2"
      + "\nThe method or field usuarioVegano is undefined for the type TestAccion2"
      + "\nThe method or field accion is undefined for the type TestAccion2"
      + "\nInvalid number of arguments. The constructor UsuarioBuilder(String, String) is not applicable for the arguments (String)"
      + "\nThis expression is not allowed in this context, since it doesn\'t cause any side effects."
      + "\nThis expression is not allowed in this context, since it doesn\'t cause any side effects."
      + "\nThis expression is not allowed in this context, since it doesn\'t cause any side effects."
      + "\n< cannot be resolved"
      + "\n> cannot be resolved"
      + "\n< cannot be resolved"
      + "\n> cannot be resolved"
      + "\nagregarBusqueda cannot be resolved"
      + "\nagregarReceta cannot be resolved"
      + "\nagregarReceta cannot be resolved"
      + "\nagregarReceta cannot be resolved"
      + "\nagregarReceta cannot be resolved"
      + "\nagregarReceta cannot be resolved"
      + "\nagregarReceta cannot be resolved"
      + "\nrecetario cannot be resolved"
      + "\nadd cannot be resolved"
      + "\naccion2 cannot be resolved");
  }
}
